//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANG_DAY
    {
        public int MA_GIANG_DAY { get; set; }
        public Nullable<int> MA_GIAO_VIEN { get; set; }
        public Nullable<int> MA_LOP { get; set; }
        public Nullable<int> MA_MON_HOC { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
    }
}
