//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STUDENTMANAGEMENTEntities1 : DbContext
    {
        public STUDENTMANAGEMENTEntities1()
            : base("name=STUDENTMANAGEMENTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BO_MON> BO_MON { get; set; }
        public virtual DbSet<CT_LOP_HOC_SINH> CT_LOP_HOC_SINH { get; set; }
        public virtual DbSet<DAN_TOC> DAN_TOC { get; set; }
        public virtual DbSet<DIEM> DIEMs { get; set; }
        public virtual DbSet<GIANG_DAY> GIANG_DAY { get; set; }
        public virtual DbSet<GIAO_VIEN> GIAO_VIEN { get; set; }
        public virtual DbSet<HANH_KIEM> HANH_KIEM { get; set; }
        public virtual DbSet<HOC_KY> HOC_KY { get; set; }
        public virtual DbSet<HOC_SINH> HOC_SINH { get; set; }
        public virtual DbSet<KHOI_LOP> KHOI_LOP { get; set; }
        public virtual DbSet<LOAI_DIEM> LOAI_DIEM { get; set; }
        public virtual DbSet<LOAI_TAI_KHOAN> LOAI_TAI_KHOAN { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<MON_HOC> MON_HOC { get; set; }
        public virtual DbSet<NAM_HOC> NAM_HOC { get; set; }
        public virtual DbSet<QUA_TRINH_HOC_MON_HOC> QUA_TRINH_HOC_MON_HOC { get; set; }
        public virtual DbSet<QUOC_TICH> QUOC_TICH { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<TON_GIAO> TON_GIAO { get; set; }
        public virtual DbSet<TRINH_DO_HOC_VAN> TRINH_DO_HOC_VAN { get; set; }
        public virtual DbSet<XEP_LOAI> XEP_LOAI { get; set; }
        public virtual DbSet<QUA_TRINH_HOC_HOC_KY> QUA_TRINH_HOC_HOC_KY { get; set; }
        public virtual DbSet<QUA_TRINH_HOC_NAM_HOC> QUA_TRINH_HOC_NAM_HOC { get; set; }
    }
}
