<<<<<<< HEAD
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON_HOC()
        {
            this.GIANG_DAY = new HashSet<GIANG_DAY>();
        }
    
        public int MA_MON_HOC { get; set; }
        public string TEN_MON_HOC { get; set; }
        public Nullable<int> MA_BO_MON { get; set; }
    
        public virtual BO_MON BO_MON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANG_DAY> GIANG_DAY { get; set; }
    }
}
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MON_HOC()
        {
            this.GIANG_DAY = new HashSet<GIANG_DAY>();
            this.QUA_TRINH_HOC_MON_HOC = new HashSet<QUA_TRINH_HOC_MON_HOC>();
        }
    
        public int MA_MON_HOC { get; set; }
        public string TEN_MON_HOC { get; set; }
        public Nullable<int> MA_BO_MON { get; set; }
        public Nullable<int> MA_KHOI_LOP { get; set; }
    
        public virtual BO_MON BO_MON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANG_DAY> GIANG_DAY { get; set; }
        public virtual KHOI_LOP KHOI_LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUA_TRINH_HOC_MON_HOC> QUA_TRINH_HOC_MON_HOC { get; set; }
    }
}
>>>>>>> origin/student
