//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAM_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAM_HOC()
        {
            this.HOC_KY = new HashSet<HOC_KY>();
        }
    
        public int MA_NAM_HOC { get; set; }
        public string TEN_NAM_HOC { get; set; }
        public Nullable<int> NAM_BAT_DAU { get; set; }
        public Nullable<int> NAM_KET_THUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOC_KY> HOC_KY { get; set; }
    }
}
