//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUA_TRINH_HOC_MON_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUA_TRINH_HOC_MON_HOC()
        {
            this.DIEMs = new HashSet<DIEM>();
        }
    
        public int MA_QTMH { get; set; }
        public Nullable<double> DIEM_TB_MON_HOC { get; set; }
        public Nullable<int> MA_QTHK { get; set; }
        public Nullable<int> MA_MON_HOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
        public virtual MON_HOC MON_HOC { get; set; }
        public virtual QUA_TRINH_HOC_HOC_KY QUA_TRINH_HOC_HOC_KY { get; set; }
    }
}
