//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUA_TRINH_HOC_HOC_KY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUA_TRINH_HOC_HOC_KY()
        {
            this.QUA_TRINH_HOC_MON_HOC = new HashSet<QUA_TRINH_HOC_MON_HOC>();
        }
    
        public int MA_QTHK { get; set; }
        public Nullable<double> DIEM_TB { get; set; }
        public Nullable<int> MA_LOP { get; set; }
        public Nullable<int> MA_HOC_SINH { get; set; }
        public Nullable<int> MA_HANH_KIEM { get; set; }
        public Nullable<int> MA_XEP_LOAI { get; set; }
        public Nullable<int> MA_HOC_KY { get; set; }
    
        public virtual HANH_KIEM HANH_KIEM { get; set; }
        public virtual HOC_KY HOC_KY { get; set; }
        public virtual HOC_SINH HOC_SINH { get; set; }
        public virtual LOP LOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUA_TRINH_HOC_MON_HOC> QUA_TRINH_HOC_MON_HOC { get; set; }
        public virtual XEP_LOAI XEP_LOAI { get; set; }
    }
}
